apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-example-deployment
spec:
  selector:
    matchLabels:
      name: cd-example
  template:
    metadata:
      labels:
        name: cd-example
    spec:
      containers:
        - name: cd-example
          image: zalerix/continuous-delivery-example:latest
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "512Mi"
          ports:
            - containerPort: 8080
              name: app-port
