apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- node-port.yaml
- deployment.yaml

images:
- name: zalerix/continuous-delivery-example:latest
  newName: alecsadam75/continuous-delivery-example
  newTag: 1.0.4
